#!/usr/bin/bash

# Add environment variables
export MATHS_MYSQL_USER=MATHS_dev
export MATHS_MYSQL_PWD=MATHS_dev_pwd
export MATHS_MYSQL_HOST=localhost
export MATHS_MYSQL_DB=MATHS_dev_db
export MATHS_TYPE_STORAGE=db


export MATHS_MYSQL_USER=maths_dev
export MATHS_MYSQL_PWD=maths_dev_pwd
export MATHS_MYSQL_HOST=localhost
export MATHS_MYSQL_DB=maths_dev_db
export MATHS_TYPE_STORAGE=db
export MATHS_API_HOST=localhost
export MATHS_API_PORT=5000
